---
- hosts: loadbalancer
  #"became" Utilizar o sudo
  become: true
  tasks:
  - name: "Instalação do NGINX via APT"
    apt: name=nginx state=present update_cache=yes

  - name: "Nginx started"
    service: name=nginx state=started enabled=yes